services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_DB: ecommerce
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres: