-- public.account definition

-- Drop table

-- DROP TABLE public.account;

CREATE TABLE public.account (
	account_id int4 NOT NULL,
	"password" varchar(255) NULL,
	user_name varchar(255) NULL,
	CONSTRAINT account_pkey PRIMARY KEY (account_id)
);


-- public."attribute" definition

-- Drop table

-- DROP TABLE public."attribute";

CREATE TABLE public."attribute" (
	attribute_id int4 NOT NULL,
	attribute_name varchar(255) NULL,
	description varchar(255) NULL,
	CONSTRAINT attribute_pkey PRIMARY KEY (attribute_id)
);


-- public.cart definition

-- Drop table

-- DROP TABLE public.cart;

CREATE TABLE public.cart (
	cart_id int4 NOT NULL,
	created_date date NULL,
	CONSTRAINT cart_pkey PRIMARY KEY (cart_id)
);


-- public.orders definition

-- Drop table

-- DROP TABLE public.orders;

CREATE TABLE public.orders (
	order_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	number_type_item int4 NULL,
	order_name varchar(255) NULL,
	order_phone varchar(255) NULL,
	order_state int4 NULL,
	ship_address varchar(255) NULL,
	total_price numeric(19, 2) NULL,
	CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);


-- public.product definition

-- Drop table

-- DROP TABLE public.product;

CREATE TABLE public.product (
	product_id int4 NOT NULL,
	category_id int4 NULL,
	created_date date NULL,
	description varchar(255) NULL,
	image varchar(255) NULL,
	price numeric(19, 2) NULL,
	product_name varchar(255) NULL,
	updated_date date NULL,
	CONSTRAINT product_pkey PRIMARY KEY (product_id)
);


-- public."role" definition

-- Drop table

-- DROP TABLE public."role";

CREATE TABLE public."role" (
	role_id varchar(255) NOT NULL,
	role_name varchar(255) NULL,
	CONSTRAINT role_pkey PRIMARY KEY (role_id)
);


-- public.account_roles definition

-- Drop table

-- DROP TABLE public.account_roles;

CREATE TABLE public.account_roles (
	accounts_account_id int4 NOT NULL,
	roles_role_id varchar(255) NOT NULL,
	CONSTRAINT account_roles_pkey PRIMARY KEY (accounts_account_id, roles_role_id),
	CONSTRAINT fkm9wvptpacgvnmui6240jwva3p FOREIGN KEY (accounts_account_id) REFERENCES public.account(account_id),
	CONSTRAINT fkms4jj38ark7ys7uw671pofbun FOREIGN KEY (roles_role_id) REFERENCES public."role"(role_id)
);


-- public.cart_item definition

-- Drop table

-- DROP TABLE public.cart_item;

CREATE TABLE public.cart_item (
	cart_item_id int4 NOT NULL,
	price numeric(19, 2) NULL,
	quantity int4 NULL,
	total_price numeric(19, 2) NULL,
	product_product_id int4 NULL,
	cart_items int4 NULL,
	CONSTRAINT cart_item_pkey PRIMARY KEY (cart_item_id),
	CONSTRAINT fkf67ig6902so02qgbxfiufjmid FOREIGN KEY (product_product_id) REFERENCES public.product(product_id),
	CONSTRAINT fkovide4bfiur6p62frq0kuda6k FOREIGN KEY (cart_items) REFERENCES public.cart(cart_id)
);


-- public.customer definition

-- Drop table

-- DROP TABLE public.customer;

CREATE TABLE public.customer (
	customer_id int4 NOT NULL,
	address varchar(255) NULL,
	created_date date NULL,
	email varchar(255) NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	phone varchar(255) NULL,
	account_account_id int4 NULL,
	cart_cart_id int4 NULL,
	CONSTRAINT customer_pkey PRIMARY KEY (customer_id),
	CONSTRAINT fk9x7okmi8dvaakw32wqqh208kv FOREIGN KEY (account_account_id) REFERENCES public.account(account_id),
	CONSTRAINT fkh8td8fqfv3u9171e9oqye30fv FOREIGN KEY (cart_cart_id) REFERENCES public.cart(cart_id)
);


-- public.order_item definition

-- Drop table

-- DROP TABLE public.order_item;

CREATE TABLE public.order_item (
	order_item_id int4 NOT NULL,
	price numeric(19, 2) NULL,
	quantity int4 NULL,
	total_price numeric(19, 2) NULL,
	product_product_id int4 NULL,
	order_items int4 NULL,
	CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id),
	CONSTRAINT fk3g20bmugoy5enhiwo850aqagk FOREIGN KEY (order_items) REFERENCES public.orders(order_id),
	CONSTRAINT fk5rg4979tfgc0krehhy6eh2e8f FOREIGN KEY (product_product_id) REFERENCES public.product(product_id)
);


-- public.product_attributes definition

-- Drop table

-- DROP TABLE public.product_attributes;

CREATE TABLE public.product_attributes (
	products_product_id int4 NOT NULL,
	attributes_attribute_id int4 NOT NULL,
	CONSTRAINT product_attributes_pkey PRIMARY KEY (products_product_id, attributes_attribute_id),
	CONSTRAINT fkgkuw18wt3grtf1pv85qad7ms0 FOREIGN KEY (attributes_attribute_id) REFERENCES public."attribute"(attribute_id),
	CONSTRAINT fkqhvbym2qw320abxw92wbwtmg3 FOREIGN KEY (products_product_id) REFERENCES public.product(product_id)
);


-- public.rating definition

-- Drop table

-- DROP TABLE public.rating;

CREATE TABLE public.rating (
	product_id int4 NOT NULL,
	description varchar(255) NULL,
	ratings int4 NULL,
	CONSTRAINT rating_pkey PRIMARY KEY (product_id),
	CONSTRAINT fknte6jmjo46jey9wh4qb7ip1sl FOREIGN KEY (ratings) REFERENCES public.product(product_id)
);