version: "3.8"

services:
  postgres:
    container_name: postgres-database-ecommerce
    image: postgres
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_DB: ecommerce
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./app:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app
  backend-ecommerce:
    image: lvquang0403/ecommerce-nashtech-backend
    container_name: ecommerce-backend
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    networks:
      - app
  frontend-ecommerce:
    image: lvquang0403/ecommerce-frontend-nextjs
    container_name: ecommerce-frontend
    ports:
      - '3000:3000'
    networks:
      - app
networks:
  app:
    name: springboot-app-network