-- public."attribute" definition

-- Drop table

-- DROP TABLE public."attribute";

CREATE TABLE public."attribute" (
                                    attribute_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    attribute_name varchar(255) NULL,
                                    description varchar(255) NULL,
                                    CONSTRAINT attribute_pkey PRIMARY KEY (attribute_id)
);


-- public.category definition

-- Drop table

-- DROP TABLE public.category;

CREATE TABLE public.category (
                                 category_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 category_name varchar(255) NULL,
                                 CONSTRAINT category_pkey PRIMARY KEY (category_id)
);


-- public."role" definition

-- Drop table

-- DROP TABLE public."role";

CREATE TABLE public."role" (
                               role_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               role_name varchar(255) NULL,
                               CONSTRAINT role_pkey PRIMARY KEY (role_id)
);


-- public.attribute_product definition

-- Drop table

-- DROP TABLE public.attribute_product;

CREATE TABLE public.attribute_product (
                                          attribute_product_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          value varchar(255) NULL,
                                          attribute_id int8 NULL,
                                          product_id int8 NULL,
                                          CONSTRAINT attribute_product_pkey PRIMARY KEY (attribute_product_id),
                                          CONSTRAINT uk5o51qv4bxm1gkpnd62kiyuqn3 UNIQUE (product_id, attribute_id)
);


-- public.cart definition

-- Drop table

-- DROP TABLE public.cart;

CREATE TABLE public.cart (
                             cart_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             created_date date NULL,
                             customer_id int8 NULL,
                             CONSTRAINT cart_pkey PRIMARY KEY (cart_id)
);


-- public.cart_item definition

-- Drop table

-- DROP TABLE public.cart_item;

CREATE TABLE public.cart_item (
                                  cart_item_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  color varchar(255) NULL,
                                  price numeric(19, 2) NULL,
                                  quantity int4 NULL,
                                  total_price numeric(19, 2) NULL,
                                  product_id int8 NULL,
                                  cart_id int8 NULL,
                                  order_item_id int8 NULL,
                                  CONSTRAINT cart_item_pkey PRIMARY KEY (cart_item_id)
);


-- public.customer definition

-- Drop table

-- DROP TABLE public.customer;

CREATE TABLE public.customer (
                                 customer_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 address varchar(255) NULL,
                                 created_date date NULL,
                                 email varchar(255) NULL,
                                 first_name varchar(255) NULL,
                                 last_name varchar(255) NULL,
                                 "password" varchar(255) NULL,
                                 phone varchar(255) NULL,
                                 user_name varchar(255) NULL,
                                 cart_id int8 NULL,
                                 CONSTRAINT customer_pkey PRIMARY KEY (customer_id)
);


-- public.customer_roles definition

-- Drop table

-- DROP TABLE public.customer_roles;

CREATE TABLE public.customer_roles (
                                       customers_customer_id int8 NOT NULL,
                                       roles_role_id int8 NOT NULL,
                                       CONSTRAINT customer_roles_pkey PRIMARY KEY (customers_customer_id, roles_role_id)
);


-- public.image definition

-- Drop table

-- DROP TABLE public.image;

CREATE TABLE public.image (
                              image_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              color varchar(255) NULL,
                              url varchar(255) NULL,
                              produc_id int8 NULL,
                              CONSTRAINT image_pkey PRIMARY KEY (image_id)
);


-- public.order_item definition

-- Drop table

-- DROP TABLE public.order_item;

CREATE TABLE public.order_item (
                                   order_item_id int8 NOT NULL,
                                   color varchar(255) NULL,
                                   price numeric(19, 2) NULL,
                                   quantity int4 NULL,
                                   total_price numeric(19, 2) NULL,
                                   product_id int8 NULL,
                                   order_id int8 NULL,
                                   CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id)
);


-- public.orders definition

-- Drop table

-- DROP TABLE public.orders;

CREATE TABLE public.orders (
                               order_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               number_type_item int4 NULL,
                               order_name varchar(255) NULL,
                               order_phone varchar(255) NULL,
                               order_state int4 NULL,
                               ship_address varchar(255) NULL,
                               total_price numeric(19, 2) NULL,
                               customer_id int8 NULL,
                               create_day date NULL,
                               CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);


-- public.product definition

-- Drop table

-- DROP TABLE public.product;

CREATE TABLE public.product (
                                product_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                created_date date NULL,
                                description text NULL,
                                price numeric(19, 2) NULL,
                                product_details varchar(255) NULL,
                                product_name varchar(255) NULL,
                                updated_date date NULL,
                                category_id int8 NULL,
                                order_item_id int8 NULL,
                                CONSTRAINT product_pkey PRIMARY KEY (product_id)
);


-- public.rating definition

-- Drop table

-- DROP TABLE public.rating;

CREATE TABLE public.rating (
                               rating_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               "comment" varchar(255) NULL,
                               create_day date NULL,
                               score int4 NULL,
                               customer_id int8 NULL,
                               product_id int8 NULL,
                               CONSTRAINT rating_pkey PRIMARY KEY (rating_id)
);


-- public.attribute_product foreign keys

ALTER TABLE public.attribute_product ADD CONSTRAINT fkmh3byg0xvw3supiufsutfx9kg FOREIGN KEY (product_id) REFERENCES public.product(product_id) ON DELETE CASCADE;
ALTER TABLE public.attribute_product ADD CONSTRAINT fkn9b873lpwtfg9wyn9fioq0ck8 FOREIGN KEY (attribute_id) REFERENCES public."attribute"(attribute_id);


-- public.cart foreign keys

ALTER TABLE public.cart ADD CONSTRAINT fkdebwvad6pp1ekiqy5jtixqbaj FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


-- public.cart_item foreign keys

ALTER TABLE public.cart_item ADD CONSTRAINT fk1uobyhgl1wvgt1jpccia8xxs3 FOREIGN KEY (cart_id) REFERENCES public.cart(cart_id) ON DELETE CASCADE;
ALTER TABLE public.cart_item ADD CONSTRAINT fkiirb0xcrkx26fc31m128hsoxx FOREIGN KEY (order_item_id) REFERENCES public.product(product_id) ON DELETE CASCADE;
ALTER TABLE public.cart_item ADD CONSTRAINT fkjcyd5wv4igqnw413rgxbfu4nv FOREIGN KEY (product_id) REFERENCES public.product(product_id);


-- public.customer foreign keys

ALTER TABLE public.customer ADD CONSTRAINT fkam4cgy6fxmjm52m8otoph84m3 FOREIGN KEY (cart_id) REFERENCES public.cart(cart_id) ON DELETE CASCADE;


-- public.customer_roles foreign keys

ALTER TABLE public.customer_roles ADD CONSTRAINT fk2dxfa4ffc0u5nwesetoy670x1 FOREIGN KEY (customers_customer_id) REFERENCES public.customer(customer_id);
ALTER TABLE public.customer_roles ADD CONSTRAINT fkjsimpx0v4lec1xdrs531x571p FOREIGN KEY (roles_role_id) REFERENCES public."role"(role_id);


-- public.image foreign keys

ALTER TABLE public.image ADD CONSTRAINT fkbq2xuqj5stuhl6eq8og1s5g7 FOREIGN KEY (produc_id) REFERENCES public.product(product_id) ON DELETE CASCADE;


-- public.order_item foreign keys

ALTER TABLE public.order_item ADD CONSTRAINT fk551losx9j75ss5d6bfsqvijna FOREIGN KEY (product_id) REFERENCES public.product(product_id);
ALTER TABLE public.order_item ADD CONSTRAINT fkt4dc2r9nbvbujrljv3e23iibt FOREIGN KEY (order_id) REFERENCES public.orders(order_id);


-- public.orders foreign keys

ALTER TABLE public.orders ADD CONSTRAINT fk624gtjin3po807j3vix093tlf FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


-- public.product foreign keys

ALTER TABLE public.product ADD CONSTRAINT fk1mtsbur82frn64de7balymq9s FOREIGN KEY (category_id) REFERENCES public.category(category_id);
ALTER TABLE public.product ADD CONSTRAINT fk40cf7ec1u2j4r6tnrqrlifn2m FOREIGN KEY (order_item_id) REFERENCES public.cart_item(cart_item_id) ON DELETE CASCADE;


-- public.rating foreign keys

ALTER TABLE public.rating ADD CONSTRAINT fk92d54lg7br8t0wb68h23u4jkn FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);
ALTER TABLE public.rating ADD CONSTRAINT fklkuwie0au2dru36asng9nywmh FOREIGN KEY (product_id) REFERENCES public.product(product_id) ON DELETE CASCADE;